[tool.poetry]
name = "{{cookiecutter.repo_name}}"
packages = [{ include = "jumpscale" }]

version = "0.1.0"
description = "{{cookiecutter.short_description}}"
authors = ["xmonader <xmonader@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
pdoc3 = "^0.6.3"
lazy-import = "^0.2.2"
pytoml = "^0.1.21"
secretconf = "^0.1.2"
better-exceptions = "^0.2.2"
ipython = "^7.6"
pynacl = "^1.3"
npyscreen = "^4.10"
click = "^7.0"
pytest = "^5.0"
codecov = "^2.0"
tox = "^3.13"
pytest-cov = "^2.7"
hypothesis = "^4.28"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
